## *LVIS Collections in MAAP STAC

### Importaing libraries

In [1]:
# import the MAAP package to handle queries
from maap.maap import MAAP

# import printing package to help display outputs
from pprint import pprint

# invoke the MAAP search client
maap = MAAP()

Unable to load config file from source maap.cfg 
Unable to load config file from source ./maap.cfg 
Unable to load config file from source /projects/maap.cfg 


In [2]:
# search all collections
results = maap.searchCollection(cmr_host="cmr.earthdata.nasa.gov")

# print the number of collections
pprint(f'Got {len(results)} results')

'Got 100 results'


### Testing LVISF1B___001

In [53]:
lvisf1b_collections = maap.searchCollection(
    short_name='LVISF1B',
    version='1',
    cmr_host='cmr.earthdata.nasa.gov'
)
lvisf1b_collections

[{'concept-id': 'C1723866745-NSIDC_ECS',
  'revision-id': '38',
  'format': 'application/echo10+xml',
  'Collection': {'ShortName': 'LVISF1B',
   'VersionId': '1',
   'InsertTime': '2023-07-26T08:11:17.836Z',
   'LastUpdate': '2023-07-26T08:11:17.836Z',
   'LongName': 'Not provided',
   'DataSetId': 'LVIS Facility L1B Geolocated Return Energy Waveforms V001',
   'Description': 'This data set contains Level-1B geolocated return energy waveforms collected by the NASA Land, Vegetation, and Ice Sensor (LVIS) Facility, an imaging lidar and camera sensor suite.',
   'DOI': {'DOI': '10.5067/XQJ8PN8FTIDG'},
   'StandardProduct': 'false',
   'RevisionDate': '2023-05-31T00:00:00.000Z',
   'SuggestedUsage': 'Scientific Research',
   'ProcessingCenter': 'NASA/GSFC/SED/ESD/LRSL',
   'ProcessingLevelId': 'Level 1B',
   'ProcessingLevelDescription': 'Sensor units',
   'ArchiveCenter': 'NASA NSIDC DAAC',
   'CollectionState': 'PLANNED',
   'RestrictionComment': ' These data are freely, openly, and ful

In [54]:
COLLECTION_ID = 'C1723866745-NSIDC_ECS' # Collection title: "NASA Shuttle Radar Topography Mission Global 1 arc second V003"

results = maap.searchGranule(
    concept_id=COLLECTION_ID,
    cmr_host="cmr.earthdata.nasa.gov"
)
pprint(f'Got {len(results)} results')


#Validating download
download = results[0].getData()
print(download)

'Got 20 results'
./LVISF1B_US2018_1107_R2011_067463.h5


In [55]:
#Testing the HDF5 files
filename = "LVISF1B_US2018_1107_R2011_067463.h5"
import h5py
with h5py.File(filename, "r") as f: 
    print("Keys: %s" % f.keys())
    # get first object name/key; may or may NOT be a group
    a_group_key = list(f.keys())[0]

    # get the object type for a_group_key: usually group or dataset
    print(type(f[a_group_key])) 

    # If a_group_key is a group name, 
    # this gets the object names in the group and returns as a list
    data = list(f[a_group_key])

    # If a_group_key is a dataset name, 
    # this gets the dataset values and returns as a list
    data = list(f[a_group_key])
    # preferred methods to get dataset values:
    ds_obj = f[a_group_key]      # returns as a h5py dataset object
    ds_arr = f[a_group_key][()]  # returns as a numpy array
    
    print(ds_arr)

Keys: <KeysViewHDF5 ['AZIMUTH', 'INCIDENTANGLE', 'LAT0', 'LAT1215', 'LFID', 'LON0', 'LON1215', 'RANGE', 'RXWAVE', 'SHOTNUMBER', 'SIGMEAN', 'TIME', 'TXWAVE', 'Z0', 'Z1215', 'ancillary_data']>
<class 'h5py._hl.dataset.Dataset'>
[159.14177  159.4966   158.7841   ... 127.461716 124.07847  124.752396]


### Testing ABLVIS1B___001

In [56]:
ablvis1b_collections = maap.searchCollection(
    short_name='ABLVIS1B',
    version='1',
    cmr_host='cmr.earthdata.nasa.gov'
)
ablvis1b_collections

[{'concept-id': 'C1513105920-NSIDC_ECS',
  'revision-id': '49',
  'format': 'application/echo10+xml',
  'Collection': {'ShortName': 'ABLVIS1B',
   'VersionId': '1',
   'InsertTime': '2023-07-26T13:13:04.560Z',
   'LastUpdate': '2023-07-26T13:13:04.560Z',
   'LongName': 'Not provided',
   'DataSetId': 'ABoVE LVIS L1B Geolocated Return Energy Waveforms V001',
   'Description': "This data set contains return energy waveform data over Alaska and Western Canada measured by the NASA Land, Vegetation, and Ice Sensor (LVIS), an airborne lidar scanning laser altimeter. The data were collected as part of NASA's Terrestrial Ecology Program campaign, the Arctic-Boreal Vulnerability Experiment (ABoVE).",
   'DOI': {'DOI': '10.5067/UMRAWS57QAFU'},
   'StandardProduct': 'false',
   'RevisionDate': '2023-07-05T00:00:00.000Z',
   'SuggestedUsage': 'Scientific Research',
   'ProcessingCenter': 'NASA/GSFC/SED/ESD/LRSL',
   'ProcessingLevelId': 'Level 1B',
   'ProcessingLevelDescription': 'Sensor units',


In [57]:
COLLECTION_ID = 'C1513105920-NSIDC_ECS' # Collection title: "NASA Shuttle Radar Topography Mission Global 1 arc second V003"

results = maap.searchGranule(
    concept_id=COLLECTION_ID,
    cmr_host="cmr.earthdata.nasa.gov"
)
pprint(f'Got {len(results)} results')


#Validating download
download = results[0].getData()
print(download)

'Got 20 results'
./LVIS1B_ABoVE2017_0629_R1803_056233.h5


In [66]:
#Testing the HDF5 files
filename = "LVIS1B_ABoVE2017_0629_R1803_056233.h5"
import h5py
with h5py.File(filename, "r") as f: 
    print("Keys: %s" % f.keys())
    # get first object name/key; may or may NOT be a group
    a_group_key = list(f.keys())[0]

    # get the object type for a_group_key: usually group or dataset
    print(type(f[a_group_key])) 

    # If a_group_key is a group name, 
    # this gets the object names in the group and returns as a list
    data = list(f[a_group_key])

    # If a_group_key is a dataset name, 
    # this gets the dataset values and returns as a list
    data = list(f[a_group_key])
    # preferred methods to get dataset values:
    ds_obj = f[a_group_key]      # returns as a h5py dataset object
    ds_arr = f[a_group_key][()]  # returns as a numpy array
    
    print(ds_arr)

Keys: <KeysViewHDF5 ['AZIMUTH', 'INCIDENTANGLE', 'LAT0', 'LAT1215', 'LFID', 'LON0', 'LON1215', 'RANGE', 'RXWAVE', 'SHOTNUMBER', 'SIGMEAN', 'TIME', 'TXWAVE', 'Z0', 'Z1215', 'ancillary_data']>
<class 'h5py._hl.dataset.Dataset'>
[209.55528 209.98833 209.2643  ... 181.83081 183.49066 182.28035]


### Testing LVISF2___001

In [60]:
lvisf2_collections = maap.searchCollection(
    short_name='LVISF2',
    version='1',
    cmr_host='cmr.earthdata.nasa.gov'
)
lvisf2_collections

[{'concept-id': 'C1723866830-NSIDC_ECS',
  'revision-id': '29',
  'format': 'application/echo10+xml',
  'Collection': {'ShortName': 'LVISF2',
   'VersionId': '1',
   'InsertTime': '2023-07-26T16:11:16.555Z',
   'LastUpdate': '2023-07-26T16:11:16.555Z',
   'LongName': 'Not provided',
   'DataSetId': 'LVIS Facility L2 Geolocated Surface Elevation and Canopy Height Product V001',
   'Description': 'This data set contains Level-2 geolocated surface elevation and canopy height measurements collected by the NASA Land, Vegetation, and Ice Sensor (LVIS) Facility, an imaging lidar and camera sensor suite.',
   'DOI': {'DOI': '10.5067/VP7J20HJQISD'},
   'StandardProduct': 'false',
   'RevisionDate': '2023-05-31T00:00:00.000Z',
   'SuggestedUsage': 'Scientific Research',
   'ProcessingCenter': 'NASA/GSFC/SED/ESD/LRSL',
   'ProcessingLevelId': 'Level 2',
   'ProcessingLevelDescription': 'Derived geophysical variables',
   'ArchiveCenter': 'NASA NSIDC DAAC',
   'CollectionState': 'PLANNED',
   'Res

In [61]:
COLLECTION_ID = 'C1723866830-NSIDC_ECS' # Collection title: "NASA Shuttle Radar Topography Mission Global 1 arc second V003"

results = maap.searchGranule(
    concept_id=COLLECTION_ID,
    cmr_host="cmr.earthdata.nasa.gov"
)
pprint(f'Got {len(results)} results')


#Validating download
download = results[0].getData()
print(download)

'Got 20 results'
./LVISF2_US2018_1107_R2011_067463.TXT


In [62]:
#Testing the TXT files from the LVIS collections
import numpy as np
data = np.genfromtxt("./LVISF2_US2018_1107_R2011_067463.TXT")
print(data)

[[1.95842916e+09 5.93768900e+06 6.74631929e+04 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 [1.95842916e+09 5.93769000e+06 6.74631931e+04 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 [1.95842916e+09 5.93769100e+06 6.74631934e+04 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 ...
 [1.95842916e+09 6.49713000e+06 6.76030543e+04 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 [1.95842916e+09 6.49713100e+06 6.76030545e+04 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 [1.95842916e+09 6.49713200e+06 6.76030548e+04 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]]


### Testing ABLVIS2___001

In [63]:
ablvis2_collections = maap.searchCollection(
    short_name='ABLVIS2',
    version='1',
    cmr_host='cmr.earthdata.nasa.gov'
)
ablvis2_collections

[{'concept-id': 'C1513105984-NSIDC_ECS',
  'revision-id': '43',
  'format': 'application/echo10+xml',
  'Collection': {'ShortName': 'ABLVIS2',
   'VersionId': '1',
   'InsertTime': '2023-07-26T10:17:49.581Z',
   'LastUpdate': '2023-07-26T10:17:49.581Z',
   'LongName': 'Not provided',
   'DataSetId': 'ABoVE LVIS L2 Geolocated Surface Elevation Product V001',
   'Description': "This data set contains surface elevation data over Alaska and Western Canada measured by the NASA Land, Vegetation, and Ice Sensor (LVIS), an airborne lidar scanning laser altimeter. The data were collected as part of NASA's Terrestrial Ecology Program campaign, the Arctic-Boreal Vulnerability Experiment (ABoVE).",
   'DOI': {'DOI': '10.5067/IA5WAX7K3YGY'},
   'StandardProduct': 'false',
   'RevisionDate': '2023-05-31T00:00:00.000Z',
   'SuggestedUsage': 'Scientific Research',
   'ProcessingCenter': 'NASA/GSFC/SED/ESD/LRSL',
   'ProcessingLevelId': 'Level 2',
   'ProcessingLevelDescription': 'Derived geophysical v

In [64]:
COLLECTION_ID = 'C1513105984-NSIDC_ECS'

results = maap.searchGranule(
    concept_id=COLLECTION_ID,
    cmr_host="cmr.earthdata.nasa.gov"
)
pprint(f'Got {len(results)} results')


#Validating download
download = results[0].getData()
print(download)

'Got 20 results'
./LVIS2_ABoVE2017_0629_R1803_056233.TXT


In [65]:
#Testing the downloaded TXT file
import numpy as np
data = np.genfromtxt("./LVIS2_ABoVE2017_0629_R1803_056233.TXT")
print(data)

[[1.95793304e+09 3.99310900e+06 5.62334890e+04 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 [1.95793304e+09 3.99311000e+06 5.62334890e+04 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 [1.95793304e+09 3.99311100e+06 5.62334890e+04 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 ...
 [1.95793306e+09 5.43227700e+06 5.65932850e+04 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 [1.95793306e+09 5.43227900e+06 5.65932850e+04 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 [1.95793306e+09 5.43228200e+06 5.65932860e+04 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]]


### Testing AFLVIS1B___001

In [69]:
aflvis1b_collections = maap.searchCollection(
    short_name='AFLVIS1B',
    version='1',
    cmr_host='cmr.earthdata.nasa.gov'
)
aflvis1b_collections

[{'concept-id': 'C1549378019-NSIDC_ECS',
  'revision-id': '43',
  'format': 'application/echo10+xml',
  'Collection': {'ShortName': 'AFLVIS1B',
   'VersionId': '1',
   'InsertTime': '2023-07-26T08:05:52.853Z',
   'LastUpdate': '2023-07-26T08:05:52.853Z',
   'LongName': 'Not provided',
   'DataSetId': 'AfriSAR LVIS L1B Geolocated Return Energy Waveforms V001',
   'Description': 'This data set contains return energy waveform data over Gabon, Africa. The measurements were taken by the NASA Land, Vegetation, and Ice Sensor (LVIS), an airborne lidar scanning laser altimeter. The data were collected as part of a NASA campaign, in collaboration with the European Space Agency (ESA) mission AfriSAR.',
   'DOI': {'DOI': '10.5067/ED5IYGVTB50Z'},
   'StandardProduct': 'false',
   'RevisionDate': '2023-05-31T00:00:00.000Z',
   'SuggestedUsage': 'Scientific Research',
   'ProcessingCenter': 'NASA/GSFC/SED/ESD/LRSL',
   'ProcessingLevelId': 'Level 1B',
   'ProcessingLevelDescription': 'Sensor units',

In [70]:
COLLECTION_ID = 'C1549378019-NSIDC_ECS' # Collection title: "NASA Shuttle Radar Topography Mission Global 1 arc second V003"

results = maap.searchGranule(
    concept_id=COLLECTION_ID,
    cmr_host="cmr.earthdata.nasa.gov"
)
pprint(f'Got {len(results)} results')


#Validating download
download = results[0].getData()
print(download)

'Got 20 results'
./LVIS1B_Gabon2016_0220_R1808_038024.h5


In [71]:
#Testing the HDF5 files
filename = "LVIS1B_Gabon2016_0220_R1808_038024.h5"
import h5py
with h5py.File(filename, "r") as f: 
    print("Keys: %s" % f.keys())
    # get first object name/key; may or may NOT be a group
    a_group_key = list(f.keys())[0]

    # get the object type for a_group_key: usually group or dataset
    print(type(f[a_group_key])) 

    # If a_group_key is a group name, 
    # this gets the object names in the group and returns as a list
    data = list(f[a_group_key])

    # If a_group_key is a dataset name, 
    # this gets the dataset values and returns as a list
    data = list(f[a_group_key])
    # preferred methods to get dataset values:
    ds_obj = f[a_group_key]      # returns as a h5py dataset object
    ds_arr = f[a_group_key][()]  # returns as a numpy array
    
    print(ds_arr)

Keys: <KeysViewHDF5 ['AZIMUTH', 'INCIDENTANGLE', 'LAT0', 'LAT1023', 'LFID', 'LON0', 'LON1023', 'RANGE', 'RXWAVE', 'SHOTNUMBER', 'SIGMEAN', 'TIME', 'TXWAVE', 'Z0', 'Z1023', 'ancillary_data']>
<class 'h5py._hl.dataset.Dataset'>
[170.88405 171.3952  179.33963 ... 178.35054 178.84067 179.31787]
